---

- name: "Overriding current vim configuration"
  include: override_vimrc.yml
  when: override_vimrc

- name: "Filling the vim configuration"
  include: fill_vimrc.yml
  when: not override_vimrc

- name: "Installing vundle plugins"
  command: vim +PluginInstall +qall
  args:
    removes: $HOME/.vim/bundle/Vundle.vim
    executable: /bin/bash    
  ignore_errors: true

- name: "Compiling the You Complete Me plugin"
  script: ~/.vim/bundle/YouCompleteMe/install.py
  args:
    removes: ~/.vim/bundle/YouCompleteMe/install.py
    executable: python3
